[package]
name = "physics"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam = "0.8.2"
glam = "0.22.0"
image = "0.24.5"
miniquad = "0.3.15"
quad-rand = "0.2.1"
rayon = "1.6.1"
